#ifndef _WINFETCH_VERSION_H
#define _WINFETCH_VERSION_H

#define WINFETCH_VERSION       "0.1.0"
#define WINFETCH_VERSION_MAJOR "0"
#define WINFETCH_VERSION_MINOR "1"
#define WINFETCH_VERSION_PATCH "0"

#endif // _WINFETCH_VERSION_H
