#ifndef _WINFETCH_VERSION_H
#define _WINFETCH_VERSION_H

#define WINFETCH_VERSION       "0.2.1"
#define WINFETCH_VERSION_MAJOR "0"
#define WINFETCH_VERSION_MINOR "2"
#define WINFETCH_VERSION_PATCH "1"

#endif // _WINFETCH_VERSION_H
