#ifndef _TIMER_VERSION_H
#define _TIMER_VERSION_H

#define TIMER_VERSION       "0.1.0"
#define TIMER_VERSION_MAJOR "0"
#define TIMER_VERSION_MINOR "1"
#define TIMER_VERSION_PATCH "0"

#endif // _TIMER_VERSION_H
