#ifndef _HASHSUM_VERSION_H
#define _HASHSUM_VERSION_H

#define HASHSUM_VERSION       "0.1.5"
#define HASHSUM_VERSION_MAJOR "0"
#define HASHSUM_VERSION_MINOR "1"
#define HASHSUM_VERSION_PATCH "5"

#endif // _HASHSUM_VERSION_H
