#ifndef _PAGER_VERSION_H
#define _PAGER_VERSION_H

#define PAGER_VERSION       "0.5.7"
#define PAGER_VERSION_MAJOR "0"
#define PAGER_VERSION_MINOR "5"
#define PAGER_VERSION_PATCH "7"

#endif // _PAGER_VERSION_H