#ifndef _COUNTER_VERSION_H
#define _COUNTER_VERSION_H

#define COUNTER_VERSION       "0.1.0"
#define COUNTER_VERSION_MAJOR "0"
#define COUNTER_VERSION_MINOR "1"
#define COUNTER_VERSION_PATCH "0"

#endif // _COUNTER_VERSION_H
